apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://github.com/dan-bull/goit-argo.git
    targetRevision: main
    path: namespaces/application
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
