apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-app
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: 'https://community-charts.github.io/helm-charts' # Helm репозиторій
    chart: mlflow
    targetRevision: 0.7.19
    helm:
      values: |
        service:
          type: ClusterIP
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ml-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true